test:
  script:
  - cd src
  - xvfb-run -s "-screen 0 1920x1080x24" python3 -m pytest --cov ./ --cov-report term --cov-report html  --junitxml unittest_results.xml

pages:
  stage: deploy
  script:
    - mv src/htmlcov  public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master