test:
  script:
  - cd src
  - xvfb-run -s "-screen 0 1920x1080x24" python3 -m pytest --cov ./ --cov-report term --cov-report html  --junitxml unittest_results.xml
  artifacts:
    paths:
      - src/htmlcov
      
pages:
  stage: deploy
  script:
    - mv src/htmlcov  public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
    
build_sdist:
  stage: deploy
  script:
    - python3 setup.py sdist
    - rm /tools/rd-plot-gui-sdist-gitlab/rdplot-*.tar.gz
    - cp dist/rdplot-*.tar.gz /tools/rd-plot-gui-sdist-gitlab/
  only:
    - master