# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
os: linux
dist: bionic

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  
services:
  - xvfb

before_install:
  - pip3 install --upgrade pip
  - pip3 install jsonpickle  setuptools
  - pip3 install 'pytest==3.10.1' 'pytest-cov==2.6.0'
  - pip3 install coveralls
  - pip3 install gitpython
  - python3 setup.py sdist

install:
    pip3 install --no-binary rdplot  dist/rdplot-*.tar.gz

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
  
script:
 - cd src
 - pytest --cov-report= --cov=rdplot

after_success:
    - coveralls
