# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 3.5
  - 3.6

before_install:
  - pip3 install jsonpickle  setuptools
  - pip3 install pytest pytest-cov
  - pip3 install coveralls
  - export git_describe=$(git describe --always)
  - echo $git_describe
  - python3 setup.py sdist

install:
    pip3 install --no-binary rdplot  dist/rdplot-*.tar.gz

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
 - cd src
 - export RUNNING_AS_UNITTEST=True
 - pytest --cov-report= --cov=rdplot

after_success:
    - coveralls

before_deploy:
  - cd ..

deploy:
  provider: pypi
  user: JensAc
  password: 
    secure: "Yl7xzj3iI0LZfdi3KxiqINdFlVsw2rgyz+WYgIqpNJAt5IJf0txw43oxmc0uBI7cW2CUoBZJloUXtgyvvbdj6uvND+ZGtNLI70AyhEaylKJNLtNQJxpZY1kJ/3109+ytdcEKPVYLsfUsAWBbtLJ4pBdIyME4xxvjj05gC1xEk9/HnQHRIR7gvpIUqLGseJ5H6Lilwx+DnWJv0FDIKH94iBACPmKU6lXRfSXbS/zFN56+O//lMgweR0At9APkTfi+EFn4f499z4cHbIWurjCfSClRpRWOYrIfQBfzSMKyI1YiZubjBzxgxsae8QwIdChRxQBmuChOAEsQ0q8WRus4XkniBwcLJ685Da82lk7ZqKfq18oRGG+3kCwRlnMfODotBI1eKXABx2NC/zkL55GaKWkfs50uNlTU1MXQ1QfIXwYeDtebNLnMQNKJi2kejuNrKPHjA1m1OSwSISTBC/L0xi7UgnzHaJwSAAtTKHc4do6IvIHOLNyc6uIt651WnJtyQc6Ow7AQu8hRqFiw6PiFackkhURfcnCwrSdwYrOZsU1eb6nY4HFcwRW4Tio8E+KYDo56RPVTWa12vfiVCBw5KspaGNABhqO5amw7jRScvXm6/gaQtgi2dv07l156l4M3Yn/T+S5ciuZhOw90TYYHDuz1oWK1WxV2/PFEqXXWtaU="
  on:
    tags: true
