# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 3.5
  - 3.6
virtualenv:
    system_site_package: true
before_install:
# - sudo add-apt-repository -y ppa:edd/misc
# - sudo apt-get update
# - sudo apt-get install -qq python-numpy python-six
# - sudo apt-get install libquantlib0-dev
# - pip3 install -r requirements.txt
 - sudo apt-get install python3-jsonpickle python3-tk  python3-pip  python3-setuptools
 - pip3 install gitversion
 - python3 setup.py sdist
 - pwd  
 - ls 
install:
    sudo pip3 install  dist/rdplrdplot-*.tar.gz
script:
 - python -m unittest discover

