# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 3.4
  - 3.5
  - 3.6
#virtualenv:
#    system_site_package: true
before_install:
# - sudo add-apt-repository -y ppa:edd/misc
# - sudo apt-get update
# - sudo apt-get install -qq python-numpy python-six
# - sudo apt-get install libquantlib0-dev
 - pip3 install -r requirements.txt
 - python3 setup.py sdist
install:
    sudo pip3 install --no-binary rdplot dist/rdplot-1.0.0.tar.gz 
script:
 - python -m unittest discover

