# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty

python:
  - 3.5
  - 3.6

before_install:
  - pip3 install jsonpickle  setuptools
  - pip3 install gitversion
  - python3 setup.py sdist

install:
    pip3 install --no-binary rdplot  dist/rdplot-*.tar.gz

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
 - cd src
 - python -m unittest discover

