# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: required
dist: trusty
python:
  - 3.5
  - 3.6
#virtualenv:
#    system_site_packages: true
before_install:
  - sudo apt-get update
# - pip3 install -r requirements.txt
#  - sudo apt-get install -y python3 python3-jsonpickle python3-tk  python3-pip  python3-setuptools
  - pip3 install jsonpickle  setuptools
  - pip3 install gitversion
  - python3 setup.py sdist
install:
    pip3 install --user --no-binary rdplot  dist/rdplot-1.0.0.tar.gz
#    sudo pip3 install  dist/rdplot-*.tar.gz
script:
 - python -m unittest discover

