# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
os: linux
dist: bionic

addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  
services:
  - xvfb

install:
  - pip3 install --upgrade pip
  - pip3 install jsonpickle  setuptools
  - pip3 install 'pytest' 'pytest-cov'
  - pip3 install coveralls
  - pip3 install gitpython
  - python3 setup.py sdist
    pip3 install --no-binary rdplot  dist/rdplot-*.tar.gz

script:
 - cd src
 - pytest --cov-report= --cov=rdplot

after_success:
    - coveralls
