image: Visual Studio 2015
platform:
  -x86
  
environment:
  matrix:
  - PYTHON: "C:\\Python36"
    PYTHON_VERSION: "3.6.1"
    PYTHON_ARCH: "32"
    PIP: "C:\\Python36\\Scripts\\pip"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: "%PIP% install cycler matplotlib py pyparsing PyQt5 pytest python-dateutil pytz sip six tabulate mpldatacursor jsonpickle xmltodict pynsist"
  - git clone https://github.com/JensAc/WinPythonModules.git
  - cd WinPythonModules
  - cmd: "%PIP% install numpy-1.13.1+mkl-cp36-cp36m-win32.whl scipy-0.19.1-cp36-cp36m-win32.whl"
  - cd ..

build_script:
  - git describe > .\src\rdplot\version.txt
  - cd src
  - python -m nsist installer.cfg

after_build:
  - cd ..

artifacts:
  - path: /build/nsis/install-rdplot.exe
  
test: off
